Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -50,6 +50,30 @@ stages:
         containerRegistry: 'acr222'
         tags: |
           $(tag)
+    - task: CmdLine@2
+      displayName: "Manifest Generation"
+      inputs: 
+        script: |-
+            export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
+            curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+            curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+            if ! cat install.sh.checksum | sha256sum --check; then
+              echo "install.sh checksum failed"
+              exit 1
+            fi
+            BINDIR="." sh install.sh
+            rm install.sh install.sh.checksum
+            ./billy generate \
+              --access-token $(System.AccessToken) \
+              --aqua-key $(AQUA_KEY) \
+              --aqua-secret $(AQUA_SECRET) \
+              --cspm-url https://asia-1.api.cloudsploit.com \
+              --artifact-path  my-image-name:${versionEnv}
+            
+              # The docker image name:tag of the newly built image
+              # --artifact-path  my-image-name:${versionEnv}        
+              # OR the path to the root folder of your project. I.e my-repo/my-app 
+              # --artifact-path  ${env.MY_APP_ROOT}
   
     # - task: Docker@2
     #   displayName: Aqua Registry Login
@@ -90,7 +114,7 @@ stages:
 
 - stage: 'Deploy'
   displayName: 'Deploy the container'
-  dependsOn: Scan
+  dependsOn: Build
   jobs:
   - deployment: Deploy
     displayName: Deploy the container
